language: scala
scala:
- 2.12.10
- 2.13.2
jdk:
- openjdk8
- openjdk11
sudo: false
cache:
  directories:
  - $HOME/.ivy2/cache
env:
  global:
    secure: P9xSHdfi5NvRIzYKO9svLwN4l6BS2NENdDPrVapMAZH30S+JPi/tpuU8o96vTMnXILW1bnMtBkWG718yVWjGn4HrKuTD91lKUMZDLgK6+nKpmrtEMcimQbwInPgCWp/GMY7XhM10KSBoe/UF7y0vAT+a3rI24pyLKTZ582Ci3n4=
script: bash bin/travis